language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install

script:
  - find src \( -name '*.php' \) -exec php -l {} \;
